import type { Metadata } from "next";
import "@/styles/globals.css";
import roboto from "../../../../../public/fonts/roboto/roboto";
import React from "react";
import BuildingManagerDashboardLayout from "@/components/BuildingManagerDashboardLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={roboto.variable}>
        <main>
          <BuildingManagerDashboardLayout>
            <section className="bp-[50px] tab:pl-[80px] tab:pt-[50px] laptopM:pl-[200px] h-screen bg-green-300">
              {children}
            </section>{" "}
          </BuildingManagerDashboardLayout>
        </main>
      </body>
    </html>
  );
}
