import type { Metadata } from "next";
import "@/styles/globals.css";
import roboto from "../../../../../public/fonts/roboto/roboto";
import React from "react";
import { auth } from "../../../../../auth";
import { cookies } from "next/headers";
import { IBuildingManager } from "@/types/building-manager-types";
import { AuthBuildingManagerServer } from "@/hooks/AuthBuildingManagerServer";
import { IJwtObject } from "@/types/constants-types";
import { redirect } from "next/navigation";
import { QueryProvider } from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const experimental_ppr = true;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  try {
    // VARS
    const session = await auth();
    const cookieStore = await cookies();
    const jwtObject = cookieStore.get("jwt") as IJwtObject;

    // FUNCTION check wether the building manager is auth or not
    const buildingManager: IBuildingManager | null =
      await AuthBuildingManagerServer({
        session,
        jwtObject,
      });

    if (!buildingManager) {
      redirect("/");
    }

    // FUNCTIONS

    // JSX JSX JSX
    if (!buildingManager) {
      return <span>You are not authenticated</span>;
    }
    return (
      <html lang="en" className="light">
        <body className={roboto.variable}>
          <QueryProvider>
            <main>{children}</main>
          </QueryProvider>
        </body>
      </html>
    );
  } catch (err: unknown) {
    if (err instanceof Error) {
      console.error(`An error occurred Error => ${err.message} `);
    } else {
      console.error("An error occurred rendering layout");
    }
  }
}
